# Generated by Django 4.2.30 on 2026-06-25 12:08

from django.db import migrations, models
import django.db.models.deletion


def copy_document_to_documents(apps, schema_editor):
    Conversation = apps.get_model('chat', 'Conversation')
    for convo in Conversation.objects.all():
        if convo.document:
            convo.documents.add(convo.document)

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_processing_progress_documentchunk_heading_and_more'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='documents',
            field=models.ManyToManyField(related_name='conversations', to='documents.document'),
        ),
        migrations.RunPython(copy_document_to_documents),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_single', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], db_index=True, max_length=20),
        ),
    ]
